// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhIXxm2i-JCG9CvJ5Ypnq-G7ZPUPHxe4E',
    appId: '1:310600942590:web:a3234fd38bf8fe5b4336af',
    messagingSenderId: '310600942590',
    projectId: 'amir-b7dcc',
    authDomain: 'amir-b7dcc.firebaseapp.com',
    storageBucket: 'amir-b7dcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-WBxiASr18bZjXhBdRgI-T_OW4xaQ-8',
    appId: '1:310600942590:android:ba9bd961d5ca1dcd4336af',
    messagingSenderId: '310600942590',
    projectId: 'amir-b7dcc',
    storageBucket: 'amir-b7dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1AH2OWFjcyJBwfOwW51DPq_B45xAWGk',
    appId: '1:310600942590:ios:65ccade2c4ac7b7f4336af',
    messagingSenderId: '310600942590',
    projectId: 'amir-b7dcc',
    storageBucket: 'amir-b7dcc.firebasestorage.app',
    iosBundleId: 'com.example.amir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1AH2OWFjcyJBwfOwW51DPq_B45xAWGk',
    appId: '1:310600942590:ios:65ccade2c4ac7b7f4336af',
    messagingSenderId: '310600942590',
    projectId: 'amir-b7dcc',
    storageBucket: 'amir-b7dcc.firebasestorage.app',
    iosBundleId: 'com.example.amir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhIXxm2i-JCG9CvJ5Ypnq-G7ZPUPHxe4E',
    appId: '1:310600942590:web:c89e61b807c5c81e4336af',
    messagingSenderId: '310600942590',
    projectId: 'amir-b7dcc',
    authDomain: 'amir-b7dcc.firebaseapp.com',
    storageBucket: 'amir-b7dcc.firebasestorage.app',
  );

}